version: "3"

services:
  grafana:
    environment:
      GF_SERVER_CERT_KEY: "/etc/ssl/live/${SSL_DOMAIN_NAME}/privkey.pem"
      GF_SERVER_CERT_FILE: "/etc/ssl/live/${SSL_DOMAIN_NAME}/cert.pem"
      GF_SERVER_DOMAIN: "${SSL_DOMAIN_NAME}"
      GF_SERVER_PROTOCOL: "https"
    ports:
      - "443:3000"
    user: "root"
    volumes:
      - "./grafana-data:/var/lib/grafana"
      - "./ssl/archive/${SSL_DOMAIN_NAME}:/etc/ssl/archive/${SSL_DOMAIN_NAME}"
      - "./ssl/live/${SSL_DOMAIN_NAME}:/etc/ssl/live/${SSL_DOMAIN_NAME}"
